// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtErw5sFfxDCodtFZj_ziUxuJgNt92o78',
    appId: '1:382333459045:web:d9039f983a7d0e361a848c',
    messagingSenderId: '382333459045',
    projectId: 'portfolio-tilda-flutter',
    authDomain: 'portfolio-tilda-flutter.firebaseapp.com',
    storageBucket: 'portfolio-tilda-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_oywxGDXwh3gJ-ZAnpHGYRL9JvLgL8o',
    appId: '1:382333459045:android:045c886edef7fe9c1a848c',
    messagingSenderId: '382333459045',
    projectId: 'portfolio-tilda-flutter',
    storageBucket: 'portfolio-tilda-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJT2jBaSmZpw6G4shyzTG8rVjhoBg8H5c',
    appId: '1:382333459045:ios:19a439fd715707161a848c',
    messagingSenderId: '382333459045',
    projectId: 'portfolio-tilda-flutter',
    storageBucket: 'portfolio-tilda-flutter.appspot.com',
    iosClientId: '382333459045-e78n10cm4d43p79a9j82j51a6n8o51de.apps.googleusercontent.com',
    iosBundleId: 'se.tildayngman.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJT2jBaSmZpw6G4shyzTG8rVjhoBg8H5c',
    appId: '1:382333459045:ios:19a439fd715707161a848c',
    messagingSenderId: '382333459045',
    projectId: 'portfolio-tilda-flutter',
    storageBucket: 'portfolio-tilda-flutter.appspot.com',
    iosClientId: '382333459045-e78n10cm4d43p79a9j82j51a6n8o51de.apps.googleusercontent.com',
    iosBundleId: 'se.tildayngman.portfolio',
  );
}
